### ISSUE TITLE
Add metrics

### ISSUE THREAD

**Issue by tomsaleeba** [adelaideecoinformatics/aekos-api#10]
Steps:
-as a user, make a series of requests to the API
-as a admin of the API, retrieve metrics on the requests that have been made to the API

Expected behaviour:
The admin user can get access to this data (doesn't have to be a UI) and can see a summary of the requests that are made.

Actual behaviour:
Currently nothing is recorded about the requests.

**Comment by tokmakoff** [comment]
Has been added via Spring Boot Actuator at the /metrics URL. Is only the metrics and no UI. That'll require further services to collect and view the data such as LogStash, Graphite etc.
