### ISSUE TITLE
Change retrieval service interface

### ISSUE THREAD

**Issue by tomsaleeba** [adelaideecoinformatics/aekos-api#11]
Currently we define the interface to return the actual data but we need to change it so that it returns a URL and an estimated time of completion.

We need to think about:
- do we always do this? Even for small stuff or do we make small requests immediately return and only push large requests off to swift. We could wait 3 seconds and if the query hasn't returned, return a JSON object that indicates {redirected: true, url: "example.com/download.csv"}. It means the client needs to handle two different cases so maybe it's not a better option
-what does the return object look like?

**Comment by tokmakoff** [comment]
We just discussed to stick with the general pattern.
Client requests and gets a response with an optional back-off time and an optional retrieval URL. Depends on how the server wants to run. If it thinks the query will take some, it can hand a back-off value  only.  If it can handle it quickly enough, it might return a retrieval URL that is local, not in the object store.

**Comment by tomsaleeba** [comment]
Do we need to worry about pagination or we'll always return a URL to a single result with everything? I'm wondering how I need to change the interface. At the moment I have two params: start and rows. Should we leave these in so people can still page (but with an option to "return all") or bin them to make people always retrieve everything?

Alternatively we could just have a simple "limit" param.

**Comment by tomsaleeba** [comment]
Closing because we've decided not to do this for now.
